package com.recoveriq.api;
import com.recoveriq.prediction.*; import com.recoveriq.optimizer.*; import com.recoveriq.synthetic.*; import com.recoveriq.persistence.*; import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
@Service public class RecoveryApplicationService {
 private final ActionConditionedRecoveryPredictionEngine predictor=new ActionConditionedRecoveryPredictionEngine(List.of(),PredictionConfig.defaults()); private final NextBestActionOptimizer optimizer=new NextBestActionOptimizer(OptimizerConfig.defaults());
 private final RecoveryAnalysisRepository repository; private final RecoveryEventRepository events; public RecoveryApplicationService(RecoveryAnalysisRepository r,RecoveryEventRepository e){repository=r;events=e;}
 @Transactional public NextBestActionResult evaluate(String customer,String payment,int amount,FailureType failure,int attempt){ var ctx=new PredictionContext(customer,CustomerArchetype.RELIABLE,amount,failure,attempt+1); var actions=List.of(RecoveryAction.IMMEDIATE_RETRY,RecoveryAction.DELAYED_RETRY,RecoveryAction.SEND_PAYMENT_LINK,RecoveryAction.REQUEST_PAYMENT_METHOD_UPDATE,RecoveryAction.STOP_RECOVERY); var result=optimizer.optimize(new OptimizationContext(payment,amount,failure,attempt),predictor.predictAll(ctx,actions)); result.selectedEvaluation().ifPresent(e->{var x=repository.findByPaymentId(payment).orElseGet(RecoveryAnalysisEntity::new);x.customerId=customer;x.paymentId=payment;x.amount=amount;x.failureType=failure.name();x.recommendedAction=e.action().name();x.probability=e.predictedSuccessProbability();x.expectedRecoveryValue=e.expectedRecoveryValue();x.reason=result.reason();repository.save(x);}); return result; }
 public RecoveryAnalysisEntity find(String payment){return repository.findByPaymentId(payment).orElseThrow(()->new NoSuchElementException("analysis not found"));}
 @Transactional public java.util.Map<String,Object> run(String customer,String payment,int amount,FailureType failure,int attempt){var existing=events.findByPaymentIdOrderByOccurredAtAsc(payment);if(!existing.isEmpty())return java.util.Map.of("paymentId",payment,"idempotent",true,"events",existing);var decision=evaluate(customer,payment,amount,failure,attempt); if(decision.selectedEvaluation().isEmpty())throw new IllegalStateException("no eligible action"); var workflow=new com.recoveriq.workflow.RecoveryWorkflow(new com.recoveriq.workflow.RecoveryWorkflow.Case(payment,amount,failure,java.time.Instant.now()),new com.recoveriq.workflow.RecoveryWorkflow.Config(2,3)); while(!workflow.terminal()){var selected=decision.selectedEvaluation().orElseThrow(); try{workflow.run(selected.action(),selected.predictedSuccessProbability(),new com.recoveriq.workflow.RecoveryWorkflow.DeterministicExecutor());}catch(IllegalStateException ex){workflow.exhaust();}} for(var event:workflow.events()){var entity=new RecoveryEventEntity();entity.paymentId=payment;entity.action=event.action().name();entity.previousState=event.previousState().name();entity.newState=event.newState().name();entity.attemptNumber=event.attemptNumber();entity.outcome=event.outcome().name();entity.occurredAt=event.timestamp();events.save(entity);} return java.util.Map.of("paymentId",payment,"finalState",workflow.state().name(),"recoveredAmount",workflow.state()==com.recoveriq.workflow.RecoveryWorkflow.State.RECOVERED?amount:0,"attemptCount",workflow.events().size()/2,"events",workflow.events()); }
 public java.util.List<RecoveryEventEntity> history(String payment){return events.findByPaymentIdOrderByOccurredAtAsc(payment);}
 public com.recoveriq.batch.BatchRecoveryEvaluator.Result batch(int size,long seed){if(size<1||size>10_000)throw new IllegalArgumentException("datasetSize must be between 1 and 10000");var generator=new SyntheticPaymentHistoryGenerator(new GeneratorConfig(seed,size,Math.min(size,100),1,12,3,java.time.Instant.parse("2025-01-01T00:00:00Z"),365,"INR",.72,GeneratorConfig.defaults().archetypeWeights(),GeneratorConfig.defaults().customerBehaviourProfiles(),.045,12,GeneratorConfig.defaults().failureTypeMultipliers(),GeneratorConfig.defaults().actionSelectionWeights(),GeneratorConfig.defaults().actionSuccessMultipliers()));var history=generator.generate();var customers=history.customers().stream().collect(java.util.stream.Collectors.toMap(Customer::customerId,java.util.function.Function.identity()));var cases=history.payments().stream().filter(p->p.attempts().getFirst().status()==AttemptStatus.FAILED).map(p->new com.recoveriq.batch.BatchRecoveryEvaluator.EvaluationCase(new com.recoveriq.workflow.RecoveryWorkflow.Case(p.paymentId(),p.amount(),p.attempts().getFirst().failureType(),p.dueAt()),customers.get(p.customerId()).archetype())).toList();return new com.recoveriq.batch.BatchRecoveryEvaluator(predictor,optimizer,new com.recoveriq.workflow.RecoveryWorkflow.Config(2,3),new com.recoveriq.workflow.RecoveryWorkflow.DeterministicExecutor()).evaluate(cases);}
}
